CREATE TABLE inventory.Item (
    ITEM_ID int GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 10 INCREMENT BY 10),
    ITEM_NAME varchar(255),
    ITEM_COUNT varchar(255),
    ITEM_DESC varchar(255)
);

insert into inventory.item(ITEM_NAME,ITEM_COUNT,ITEM_DESC) values('Milk','20','Organic Milk with Vitamin D')
insert into inventory.item(ITEM_NAME,ITEM_COUNT,ITEM_DESC) values('Eggs','10','Organic Large Eggs');
insert into inventory.item(ITEM_NAME,ITEM_COUNT,ITEM_DESC) values('Bread','16','brown Bread with multigrains');
insert into inventory.item(ITEM_NAME,ITEM_COUNT,ITEM_DESC) values('Coffee','17','Decaf Coffee');
insert into inventory.item(ITEM_NAME,ITEM_COUNT,ITEM_DESC) values('Cake','9','Sugar Free Gluten Free Cake');

create index itemid_index on inventory.item(ITEM_ID)

select * from inventory.item